// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection, updateProviderConnectionByEmail,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey, validateApiKey,
  getOrCreateInternalApiKey, getApiKeyLookupMap, hashApiKey,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getSystemPrompts, getSystemPromptById, getSystemPromptByModel,
  getLivePromptsForModel, getAllLivePrompts,
  createSystemPrompt, updateSystemPrompt, deleteSystemPrompt,
  getModelSkills, getModelSkillById, getModelSkillsForModel,
  getActiveSkillIdsForModel, getModelsForSkill, getPrefixForProvider,
  createModelSkill, updateModelSkill, deleteModelSkill, setModelSkillActive,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  exportDb, importDb,
} from "../lib/db/index.js";
